config:
  # Every Vagrant development environment requires a box. See: https://atlas.hashicorp.com/search
  vagrant_box: 'ajnijland/centos6-php7-elasticsearch-mysql'
  vagrant_box_version: '0.2.0'
  # Should be either nginx or apache
  webserver: 'nginx'
  private_box_ip: '192.168.56.191'
  timezone: 'Europe/Amsterdam'
  memory: '2048'
  cpus: '2'
  git_config_user_name: 'Your Name'
  git_config_user_email: 'info@example.com'
  database_scripts: ['./box/data/database_import.sql']
  # The known hosts that should be added to the known hosts file (can be useful for the clone of your git repo)
  known_hosts: [
    'bitbucket.org',
    'github.com'
  ]
  restart_services: [
    'elasticsearch'
  ]
  copy_files: [
    {
      file: './box/templates/hosts',
      copy_to: '/etc/hosts'
    }
  ]
  commands: []
  projects: [
    {
      # The domain name of the site for the vhost
      domain: 'dev.project.com',
      # The web directory seen from the project directory
      web_dir: 'web',
      # Repository that should be checked out on provisioning
      git_repo: '-b master git@github.com:silexphp/Silex-Skeleton.git',
      # Whether or not composer install should be triggered on provisioning
      composer_install: true,
      # Directory where composer install must be triggered (seen from the project dir)
      composer_install_dir: ".",
      commands: [
        {
          #current directory is project directory
          execute_dir: ".",
          command: "php bin/console my-command"
        },
        {
          execute_dir: "web",
          command: 'rm -rf index_*'
        }
      ]
    }
  ]
